name: java-ci
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
          cache: "maven"
        
      - name: build package
        run: mvn clean package
        #coverage at 27
      - name: Sonar cloud
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ vars.PROJECT_NAME }} \
            -Dsonar.organization=${{ vars.ORG_NAME }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_REAL_TIME }}

      - name: Create a Artifact
        uses: actions/upload-artifact@v4
        with:
          name: real-time
          path: "./target/*.jar"
      
      # - name: Configure AWS Cerdentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Upload Jar to S3
      #   run: |
      #     aws s3 cp target/health-monitor-0.0.1-SNAPSHOT.jar \
      #     s3://${{ secrets.S3_BUCKET_NAME }}/
      