name: java-ci
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
        
      - name: build package
        run: mvn clean package
      
      - name: Sonar cloud
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ vars.PROJECT_NAME }} \
            -Dsonar.organization=${{ vars.ORG_NAME }} \
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_REAL_TIME }}